#!/bin/bash

echo "Test 1: Empty string ''"
./Static_Cast ""
echo "Expected:"
echo "char: impossible"
echo "int: impossible"
echo "float: impossible"
echo "double: impossible"
echo "-------------"

echo "Test 2: Not-a-number 'nan'"
./Static_Cast "nan"
echo "Expected:"
echo "char: impossible"
echo "int: impossible"
echo "float: nanf"
echo "double: nan"
echo "-------------"

echo "Test 3: Infinite 'inf'"
./Static_Cast "inf"
echo "Expected:"
echo "char: impossible"
echo "int: impossible"
echo "float: +inff"
echo "double: +inf"
echo "-------------"

echo "Test 4: Negative Infinite '-inf'"
./Static_Cast "-inf"
echo "Expected:"
echo "char: impossible"
echo "int: impossible"
echo "float: -inff"
echo "double: -inf"
echo "-------------"

echo "Test 5: Float Not-a-number 'nanf'"
./Static_Cast "nanf"
echo "Expected:"
echo "char: impossible"
echo "int: impossible"
echo "float: nanf"
echo "double: nan"
echo "-------------"

echo "Test 6: Printable char 'A'"
./Static_Cast "A"
echo "Expected:"
echo "char: 'A'"
echo "int: 65"
echo "float: 65.0f"
echo "double: 65.0"
echo "-------------"

echo "Test 7: Non-printable char (ASCII 2)"
./Static_Cast "$(printf "\x02")"
echo "Expected:"
echo "char: Non displayable"
echo "int: 2"
echo "float: 2.0f"
echo "double: 2.0"
echo "-------------"

echo "Test 8: Integer in range '123'"
./Static_Cast "123"
echo "Expected:"
echo "char: '{'"
echo "int: 123"
echo "float: 123.0f"
echo "double: 123.0"
echo "-------------"

echo "Test 9: Integer overflow (exceeding INT_MAX)"
./Static_Cast "2147483648"
echo "Expected:"
echo "char: impossible"
echo "int: impossible"
echo "float: impossible"
echo "double: impossible"
echo "-------------"

echo "Test 10: 0"
./Static_Cast "0"
echo char: "Non displayabl"e
echo int: "0"
echo float: "0.0f"
echo double: "0.0"
echo "-------------"
